file del VI_09-11-22
7clickers/ShowRoom3D pull request #26
Opened 2022-11-21 17:12 UTC by norislav

Creazione nuovo branch e commit dei file del verbale. #6

2022-11-28 12:10 UTC, mirkostella commented on latex/interni/verbali/verbale_interno_09-11-22/config/changelog_input.tex
> +	0.0.1 & 09-11-22 & Rino Sincic & - &  Redazione documento\\
Inserire ruolo Rino

2022-11-28 12:13 UTC, mirkostella requested changes
Eliminare i file .log

2022-11-29 11:07 UTC, mirkostella approved these changes

2022-12-01 09:50 UTC, Manto00 approved these changes

2022-12-01 11:00 UTC, merged