Glossario
7clickers/ShowRoom3D pull request #60
Opened 2022-12-14 18:17 UTC by Manto00

2022-12-16 11:08 UTC, mirkostella commented
cancellare il file txt di prova dopo aver controllato che lo script funzioni correttamente

2022-12-20 17:29 UTC, ElenaPand requested changes
Da correggere un po' di errori di battitura e le E' all'inizio delle frasi.

2022-12-20 17:29 UTC, ElenaPand commented on latex/esterni/doc_esterna/glossario/config/changelog_input.tex
> +	0.0.4 & 12-12-22 & Giacomo Mason & Analista &  definiti alcuni termini \tabularnewline
```suggestion
	0.0.4 & 12-12-22 & Giacomo Mason & Analista &  Definiti alcuni termini \tabularnewline
```

2022-12-20 17:29 UTC, ElenaPand commented on latex/esterni/doc_esterna/glossario/res/sections/alphabet/a/a.tex
> +il documento o file viene convalidato dal responsabile di progetto
```suggestion
Il documento o file viene convalidato dal responsabile di progetto.
```

2022-12-20 17:29 UTC, ElenaPand commented on latex/esterni/doc_esterna/glossario/res/sections/alphabet/d/d.tex
> +E' una piattaforma che permette la comunicazione attraverso chiamate vocali, videochiamate e messaggi di testo.  Inoltre offre la possibilità di condividere media e file.
```suggestion
Piattaforma che permette la comunicazione attraverso chiamate vocali, videochiamate e messaggi di testo.  Inoltre offre la possibilità di condividere media e file.
```

2022-12-20 17:29 UTC, ElenaPand commented on latex/esterni/doc_esterna/glossario/res/sections/alphabet/e/e.tex
> +E' un programma dedicato alla produzione e gestione di folgi elettronici.
```suggestion
Programma dedicato alla produzione e gestione di fogli elettronici.
```

2022-12-20 17:29 UTC, ElenaPand commented on latex/esterni/doc_esterna/glossario/res/sections/alphabet/f/f.tex
> +É un'architettura logica di supporto sulla quale un software può essere progettato e realizzato, con lo scopo di facilitare lo sviluppo da parte del programmatore.
```suggestion
Architettura logica di supporto sulla quale un software può essere progettato e realizzato, con lo scopo di facilitare lo sviluppo da parte del programmatore.
```

2022-12-20 17:29 UTC, ElenaPand commented on latex/esterni/doc_esterna/glossario/res/sections/alphabet/p/p.tex
> +E' una lavagna digitale che che rappresenta in modo semplice e chiaro lo stato di avanzamento del progetto. La lavagna è suddivisa in colonne ed ognuna rappresenta uno stato.  Le issue vengono posizi
```suggestion
Lavagna digitale che che rappresenta in modo semplice e chiaro lo stato di avanzamento del progetto. La lavagna è suddivisa in colonne ed ognuna rappresenta uno stato.  Le issue vengono posizionate in una delle colonne in base alla loro condizione.
```

2023-01-05 17:08 UTC, ElenaPand approved these changes

2023-01-05 22:02 UTC, merged