Piano di qualifica
7clickers/ShowRoom3D pull request #68
Opened 2023-01-04 17:16 UTC by mirkostella

2023-01-25 09:22 UTC, ElenaPand requested changes
Io metterei come subsubsections i titoli tipo: "Processi Primari" ecc... così si vedono nell'indice.

2023-01-25 09:22 UTC, ElenaPand commented on latex/esterni/doc_esterna/piano_di_qualifica/config/changelog_input.tex
> +\changelogTable{
l'ordine delle modifiche è al contrario

2023-01-25 09:22 UTC, ElenaPand commented on latex/esterni/doc_esterna/piano_di_qualifica/res/sections/01_content.tex
> +	Funzionalità & Garantire con accuratezza e conformità le funzionalità poste nel documento di Analisi dei Requisiti & MPD01, MPD02\tabularnewline
Analisi dei Requisiti in corsivo

2023-02-12 15:53 UTC, ElenaPand approved these changes

2023-03-07 16:05 UTC, mirkostella commented on latex/esterni/doc_esterna/piano_di_qualifica/config/tracking_input.tex
> +}
questo file non dovrebbe esserci.. dimenticanza nel cancellarlo?

2023-03-07 16:27 UTC, mirkostella commented on latex/esterni/doc_esterna/piano_di_qualifica/res/sections/02_misurazioni.tex
> +In questa sezione vengono riportati i risultati dell'attività di verifica effettuata relativa alla qualità del processo
manca il punto a fine frase

2023-03-07 16:53 UTC, mirkostella commented on latex/esterni/doc_esterna/piano_di_qualifica/res/sections/02_misurazioni.tex
> +	Studio di fattibilità & 80 & Superato\tabularnewline
lanciare nuovo script su questo file: elementi trovati -       Glossario & 74 & Superato\tabularnewline
-       Norme di progetto & 68 & Superato\tabularnewline
-       Piano di progetto & 79 & Superato\tabularnewline
-       Piano di qualifica & 74 & Superato\tabularnewline
+       \textit{Glossario} & 74 & Superato\tabularnewline
+       \textit{Norme di Progetto} & 68 & Superato\tabularnewline
+       \textit{Piano di Progetto} & 79 & Superato\tabularnewline
+       \textit{Piano di Qualifica} & 74 & Superato\tabularnewline

2023-03-19 10:49 UTC, GiacomoMaso commented on latex/esterni/doc_esterna/piano_di_qualifica/res/sections/02_misurazioni.tex
> +	VI 23-03-16 & 67 & Superato\tabularnewline
correggere data su tutti verbali, adesso in formato YY-MM-DD

2023-03-19 10:50 UTC, GiacomoMaso approved these changes

2023-03-19 23:57 UTC, Manto00 approved these changes

2023-03-20 00:00 UTC, merged