Casi uso
7clickers/ShowRoom3D pull request #76
Opened 2023-01-11 10:06 UTC by TommasoAllegretti

#48

2023-01-13 13:04 UTC, mirkostella commented
Mi sono aggiunto come verificatore per questo documento perché molto importante per la prima revisione e avrei dei punti da chiarire

2023-01-13 13:10 UTC, mirkostella requested changes
discutere prima di mergiare

2023-01-14 03:32 UTC, mirkostella commented
parti mancanti (verrà creata una issue associata a questa pull con i punti che decideremo di tenere o aggiungere a quelli sotto riportati):

- [ ] Se si decide di lasciare i casi d'uso obbligatori colorati di azzurro si deve indicare cosa indica il colore nello schema in quanto non é standard UML (le funzionalità azzurre sono quelle facoltative);
- [ ] Manca la riga relativa a RF1 (simulazione acquisto oggetti) nella tabella che elenca i requisiti;
- [ ] aggiungere un page break dopo ogni funzionalità principale (UC1,UC2,UC3 ecc...);
- [ ] RF1.2 specificare nella descrizione che gli oggetti vengono rimossi tutti con un singolo comando;
- [ ] Nel testo della descrizione indicare che l'utente "puó" e non "deve poter" perché si tratta di una funzionalità offerta e non di un elenco di cose da fare;
- [ ] Aggiungere una colonna con il nome del caso d’uso (ho notato che alcune descrizioni sono ambigue se non si conosce il nome della funzionalità es: riposizionamento oggetto o utente?);
- [ ] modificare sezione attori ed aggiungere voce attore principale nei vari casi: va specificato l'utente che può accedere alla funzionalità anche se il progetto prevede un solo attore (come nei casi d'uso testuale). Inoltre scrivere una definizione di "Utente in ambiente 3D" anche se semplice;
- [ ] RF2.1 modificare descrizione: l'utente puó visualizzare la lista degli oggetti presenti nel carrello;
- [ ] Aggiungere accento su quantità nel UC2.1.1.4;
- [ ] Aggiungere UC2.1.1.5: Vis. caratteristiche fisiche oggetto (come specificato nella mail di Alex Beggiato);
- [ ] Modificare nome UC4.2: “compiere rotazioni camera” in quanto “compiere spostamenti camera” potrebbe essere frainteso come cambiare prospettiva o angolazione;
- [ ] Modificare descrizione RF6: L’utente visualizza un messaggio di “oggetto non modificabile” quando tenta di modificare un oggetto non modificabile. (Non viene messo “puó visualizzare” perché non é una cosa che dipende da un’azione dell’utente);
- [ ] RF7 ed RF7.1 nella tabella sono messi come obbligatori ma sono facoltativi;
- [ ]  RF1 “rimozione oggetti dal carrello” e tutti i suoi sottovasi sono messi come obbligatori ma sono facoltativi;
- [ ]  Aggiungere sottocasi di UC4.1 in quanto i movimenti lungo l’asse z sono facoltativi ma non viene indicato da nessuna parte (di conseguenza modificare la descrizione di UC4.1 indicando solo X,Y in quanto Z facoltativo);
- [ ] Modificare il nome di UC1 da “simulazione acquisto oggetti” in “rimozione oggetti dal carrello” (va modificato anche nell’immagine UML);
- [ ] Dubbio riposizionamento (potrebbe essere una generalizzazione) quindi i sottocasi sono due funzionalità separate.. potrebbe valere anche per rimozione oggetti carrello;
- [ ] Eliminare sezione “requisiti qualitativi” per i seguenti motivi: RQ1 errato in quanto fa riferimento ad un documento interno del quale il proponente ed il committente potrebbero non avere accesso in un contesto di lavoro reale oltre a non fornire dettagli concreti di qualità;RQ2 La pubblicazione del codice in un repo non implica la qualità dello stesso;RQ3 legato alla qualità di processo stesura documenti e non del prodotto;
- [ ] Rinominare sezione “requisiti di vincolo” in “requisiti di dominio” e tutti gli RV nella tabella e la lettera di tipologia;
- [ ] toglierei come vincolo di dominio RV4 in quanto é stata una decisione nostra e non imposta da qualche vincolo tecnologico del proponente. Aggiungerei informazioni di questo tipo nella sezione "descrizione generale” o altra;
Se volete che indichi nel codice i miei suggerimenti fatemi sapere (ho preparato questo elenco per non aggiungere molti commenti spezzati visto la quantità).

2023-02-13 15:06 UTC, ElenaPand approved these changes

2023-02-13 15:06 UTC, closed without merging