sistemazione struttura norme_di_progetto
7clickers/ShowRoom3D pull request #99
Opened 2023-02-03 16:58 UTC by mirkostella

sono stati aggiunti i file sulla documentazione prodotta alla struttura di norme_di_progetto.. inoltre sono state fatte altre piccole modifiche da controllare

2023-02-03 17:00 UTC, mirkostella commented
avrei potuto fare il merge direttamente con norme di progetto ma preferisco che diate un'occhiata anche voi per discutere separatamente i miei cambiamenti... da finire la stesura di alcuni tipi di documenti

2023-02-04 17:11 UTC, mirkostella commented
non ho lanciato lo script nella sezione piano di progetto... verrà incluso nel prossimo commit

2023-02-06 15:03 UTC, mirkostella commented
ho terminato ed aspetto indicazioni per fare le correzioni o aggiunte

2023-02-07 15:02 UTC, ElenaPand requested changes
- [ ] il diario di bordo penso vada spostato sotto documentazione esterna
- [ ] i paragrafi "Struttura Lettera di presentazione" e tutti quelli analoghi per gli altri documenti non saprei se farli comparire nell'indice, lasciarli così o togliere semplicemente il titolo
- [ ] ci sono tanti elenchi puntati ripetuti, in cui prima c'è l'elenco delle sezioni e poi la descrizione di esse: non saprei se comprimerli in un solo elenco puntato o lasciare così
- [ ] sezione norme di progetto: è tanto specifica e molte cose vengono ripetute all'inizio delle varie sezioni del documento stesso. Forse sarebbero da rendere le descrizioni meno approfondite

2023-02-07 15:40 UTC, mirkostella commented on latex/interni/doc_interna/norme_di_progetto/res/sections/documentazione/documentazione_prodotta/piano_di_progetto.tex
> +\textbf{NOTA:} ogni tabella o immagine all'interno del documento verrà indicata anche nell'indice del documento stesso in modo che sia rintracciabile con
queste sezioni devono descrivere come vanno fatti i documenti (way of working) e non devono comparire qua riferimenti alle tabelle o immagini contenute nei documenti stesi. Queste sezioni dovrebbero essere fatte prima di creare il documento... noi lo stiamo facendo dopo ma non dovrebbe essere cosi

2023-02-07 15:44 UTC, mirkostella commented on latex/interni/doc_interna/norme_di_progetto/res/sections/documentazione/documentazione_prodotta/piano_di_qualifica.tex
> +I dettagli su come vengono applicate tali metriche vengono poi descritti nelle \textit{Norme di Progetto}.
non indicherei le sezioni perché i numeri di sezione possono variare frequentemente con la continua modifica dei documenti e diventerebbe difficile rendere coerente in ogni momento la documentazione. (in un caso che sistemeró mi sono appena contraddetto)

2023-02-07 15:47 UTC, mirkostella commented on latex/interni/doc_interna/norme_di_progetto/res/sections/documentazione/documentazione_prodotta/piano_di_qualifica.tex
> +I dettagli su come vengono applicate tali metriche vengono poi descritti nelle \textit{Norme di Progetto}.
nel senso che eviterei di scrivere robe del tipo: come descritto nella sezione x o bisognerebbe scrivere una norma che impedisca di aggiungere sezioni che vadano a modificare il numero di sezione delle altre.

2023-02-07 15:47 UTC, mirkostella commented on latex/interni/doc_interna/norme_di_progetto/res/sections/documentazione/documentazione_prodotta/piano_di_qualifica.tex
> +I dettagli su come vengono applicate tali metriche vengono poi descritti nelle \textit{Norme di Progetto}.
vedi altro commento simile

2023-02-07 15:54 UTC, mirkostella commented
1.  il diario di bordo penso vada spostato sotto documentazione esterna

2.  i paragrafi "Struttura Lettera di presentazione" e tutti quelli analoghi per gli altri documenti non saprei se farli comparire nell'indice, lasciarli così o togliere semplicemente il titolo
3.  ci sono tanti elenchi puntati ripetuti, in cui prima c'è l'elenco delle sezioni e poi la descrizione di esse: non saprei se comprimerli in un solo elenco puntato o lasciare così
4. sezione norme di progetto: è tanto specifica e molte cose vengono ripetute all'inizio delle varie sezioni del documento stesso. Forse sarebbero da rendere le descrizioni meno approfondite  

COMMENTI MIRKO

1. concordo
2. ho scelto di fare così per non rendere troppo articolato l'indice
3. ho scelto di fare prima l'elenco e poi le descrizioni per avere una visuale compatta dell'elenco ma volendo possiamo includere le descrizioni direttamente nell'elenco
4. ok anche perché le descrizioni sarebbero contenuto da scrivere nella parte specifica.. se vedo che la descrizione che ho messo é più precisa di quella scritta nella sezione del documento posso sostituirla?

2023-02-10 17:01 UTC, ElenaPand approved these changes

2023-02-10 17:03 UTC, merged